-- MANTO RESENHA — configuração do Supabase
-- Pode ser executado novamente com segurança no SQL Editor.

create table if not exists public.catalog_overrides (
  product_id text primary key,
  hidden boolean not null default false,
  sizes text[] not null default '{}'
);

create table if not exists public.custom_products (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  image_url text not null,
  sizes text[] not null default '{}',
  hidden boolean not null default false
);

create table if not exists public.customer_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_interests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  cep text not null,
  address text not null,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.catalog_overrides enable row level security;
alter table public.custom_products enable row level security;
alter table public.customer_profiles enable row level security;
alter table public.order_interests enable row level security;

-- Permissões de API explícitas
grant usage on schema public to anon, authenticated;
grant select on public.catalog_overrides to anon, authenticated;
grant select on public.custom_products to anon, authenticated;
grant insert on public.order_interests to anon, authenticated;
grant select on public.customer_profiles to authenticated;
grant all on public.catalog_overrides to authenticated;
grant all on public.custom_products to authenticated;
grant select on public.order_interests to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant usage, select on sequence public.order_interests_id_seq to anon;

-- Catálogo: visitantes enxergam apenas camisas personalizadas ativas.
drop policy if exists "public read overrides" on public.catalog_overrides;
create policy "public read overrides" on public.catalog_overrides
for select to anon, authenticated using (true);

drop policy if exists "public read custom" on public.custom_products;
create policy "public read custom" on public.custom_products
for select to anon, authenticated using (hidden = false);

-- Administração: somente o e-mail abaixo pode incluir, alterar, ocultar e excluir.
drop policy if exists "admin manage overrides" on public.catalog_overrides;
create policy "admin manage overrides" on public.catalog_overrides
for all to authenticated
using (lower(auth.jwt()->>'email') = 'jvsoubihe@gmail.com')
with check (lower(auth.jwt()->>'email') = 'jvsoubihe@gmail.com');

drop policy if exists "admin manage custom" on public.custom_products;
create policy "admin manage custom" on public.custom_products
for all to authenticated
using (lower(auth.jwt()->>'email') = 'jvsoubihe@gmail.com')
with check (lower(auth.jwt()->>'email') = 'jvsoubihe@gmail.com');

-- O admin também precisa enxergar camisas personalizadas ocultas.
drop policy if exists "admin read hidden custom" on public.custom_products;
create policy "admin read hidden custom" on public.custom_products
for select to authenticated
using (lower(auth.jwt()->>'email') = 'jvsoubihe@gmail.com');

-- Clientes enxergam o próprio cadastro; admin enxerga todos.
drop policy if exists "profile own read" on public.customer_profiles;
create policy "profile own read" on public.customer_profiles
for select to authenticated
using (id = auth.uid() or lower(auth.jwt()->>'email') = 'jvsoubihe@gmail.com');

-- Interesse de compra pode ser registrado por visitante ou cliente; só admin lista tudo.
drop policy if exists "interest insert" on public.order_interests;
create policy "interest insert" on public.order_interests
for insert to anon, authenticated with check (true);

drop policy if exists "admin read interests" on public.order_interests;
create policy "admin read interests" on public.order_interests
for select to authenticated
using (lower(auth.jwt()->>'email') = 'jvsoubihe@gmail.com');

-- Cria automaticamente um perfil quando um usuário é cadastrado.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.customer_profiles(id, email)
  values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute procedure public.handle_new_user();
