-- MANTO RESENHA - execute este arquivo no SQL Editor do Supabase
create table if not exists public.catalog_overrides (product_id text primary key, hidden boolean default false, sizes text[] default '{}');
create table if not exists public.custom_products (id bigint generated by default as identity primary key, name text not null, type text not null, image_url text not null, sizes text[] default '{}', hidden boolean default false);
create table if not exists public.customer_profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null, created_at timestamptz default now());
create table if not exists public.order_interests (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete set null, email text, cep text not null, address text not null, items jsonb not null default '[]'::jsonb, created_at timestamptz default now());

alter table public.catalog_overrides enable row level security; alter table public.custom_products enable row level security; alter table public.customer_profiles enable row level security; alter table public.order_interests enable row level security;

-- Leitura pública do catálogo
drop policy if exists "public read overrides" on public.catalog_overrides; create policy "public read overrides" on public.catalog_overrides for select using (true);
drop policy if exists "public read custom" on public.custom_products; create policy "public read custom" on public.custom_products for select using (true);

-- Administração: somente o e-mail definido como administrador
drop policy if exists "admin manage overrides" on public.catalog_overrides; create policy "admin manage overrides" on public.catalog_overrides for all to authenticated using ((auth.jwt()->>'email')='jvsoubihe@gmail.com') with check ((auth.jwt()->>'email')='jvsoubihe@gmail.com');
drop policy if exists "admin manage custom" on public.custom_products; create policy "admin manage custom" on public.custom_products for all to authenticated using ((auth.jwt()->>'email')='jvsoubihe@gmail.com') with check ((auth.jwt()->>'email')='jvsoubihe@gmail.com');

-- Clientes podem ver o próprio cadastro; admin vê todos
drop policy if exists "profile own read" on public.customer_profiles; create policy "profile own read" on public.customer_profiles for select to authenticated using (id=auth.uid() or (auth.jwt()->>'email')='jvsoubihe@gmail.com');

-- Interesse pode ser registrado por visitante ou cliente; somente admin lê tudo
drop policy if exists "interest insert" on public.order_interests; create policy "interest insert" on public.order_interests for insert to anon, authenticated with check (true);
drop policy if exists "admin read interests" on public.order_interests; create policy "admin read interests" on public.order_interests for select to authenticated using ((auth.jwt()->>'email')='jvsoubihe@gmail.com');

-- Cria automaticamente o perfil ao cadastrar usuário
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.customer_profiles(id,email) values(new.id,new.email) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
